// <auto-generated />
using System;
using CommonGround.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommonGround.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommonGround.Modules.Audit.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComparisonSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResponseSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.ComparisonParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComparisonSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResponseSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ResponseSetId");

                    b.HasIndex("ComparisonSessionId", "ResponseSetId")
                        .IsUnique();

                    b.ToTable("ComparisonParticipants");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.ComparisonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ComparisonSessions");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComparisonSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviterLabel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("InviterResponseSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonSessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.AnswerOptionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId", "Locale")
                        .IsUnique();

                    b.ToTable("AnswerOptionTranslations");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.DimensionMaxScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireVersionId", "DimensionId")
                        .IsUnique();

                    b.ToTable("DimensionMaxScores");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.DimensionWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnswerOptionId", "DimensionId")
                        .IsUnique();

                    b.ToTable("DimensionWeights");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SectionIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireVersionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.QuestionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Locale")
                        .IsUnique();

                    b.ToTable("QuestionTranslations");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.QuestionnaireVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("QuestionnaireVersions");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("DimensionGroups");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DimensionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DimensionGroupId");

                    b.ToTable("DimensionGroupMemberships");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroupTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DimensionGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionGroupId", "Locale")
                        .IsUnique();

                    b.ToTable("DimensionGroupTranslations");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("NormalisedScore")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<decimal>("RawScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("ResponseSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResponseSetId", "DimensionId")
                        .IsUnique();

                    b.ToTable("DimensionScores");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId", "Locale")
                        .IsUnique();

                    b.ToTable("DimensionTitles");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.InsightSnippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.ToTable("InsightSnippets");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.InsightSnippetTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InsightSnippetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InsightSnippetId", "Locale")
                        .IsUnique();

                    b.ToTable("InsightSnippetTranslations");
                });

            modelBuilder.Entity("CommonGround.Modules.Responses.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrimaryAnswerOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponseSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondaryAnswerOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResponseSetId", "QuestionId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CommonGround.Modules.Responses.Entities.ResponseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessCodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PrivateResultTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ResponseSets");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.ComparisonParticipant", b =>
                {
                    b.HasOne("CommonGround.Modules.Comparisons.Entities.ComparisonSession", "ComparisonSession")
                        .WithMany("Participants")
                        .HasForeignKey("ComparisonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComparisonSession");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.Invite", b =>
                {
                    b.HasOne("CommonGround.Modules.Comparisons.Entities.ComparisonSession", null)
                        .WithMany()
                        .HasForeignKey("ComparisonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.AnswerOption", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.AnswerOptionTranslation", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.AnswerOption", null)
                        .WithMany()
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.DimensionMaxScore", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.QuestionnaireVersion", "QuestionnaireVersion")
                        .WithMany("DimensionMaxScores")
                        .HasForeignKey("QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionnaireVersion");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.DimensionWeight", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.AnswerOption", "AnswerOption")
                        .WithMany("DimensionWeights")
                        .HasForeignKey("AnswerOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerOption");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.Question", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.QuestionnaireVersion", "QuestionnaireVersion")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionnaireVersion");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.QuestionTranslation", b =>
                {
                    b.HasOne("CommonGround.Modules.Questionnaires.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroupMembership", b =>
                {
                    b.HasOne("CommonGround.Modules.Reporting.Entities.DimensionGroup", "DimensionGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("DimensionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionGroup");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroupTranslation", b =>
                {
                    b.HasOne("CommonGround.Modules.Reporting.Entities.DimensionGroup", null)
                        .WithMany()
                        .HasForeignKey("DimensionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.InsightSnippetTranslation", b =>
                {
                    b.HasOne("CommonGround.Modules.Reporting.Entities.InsightSnippet", null)
                        .WithMany()
                        .HasForeignKey("InsightSnippetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommonGround.Modules.Responses.Entities.Answer", b =>
                {
                    b.HasOne("CommonGround.Modules.Responses.Entities.ResponseSet", "ResponseSet")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponseSet");
                });

            modelBuilder.Entity("CommonGround.Modules.Comparisons.Entities.ComparisonSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.AnswerOption", b =>
                {
                    b.Navigation("DimensionWeights");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("CommonGround.Modules.Questionnaires.Entities.QuestionnaireVersion", b =>
                {
                    b.Navigation("DimensionMaxScores");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CommonGround.Modules.Reporting.Entities.DimensionGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("CommonGround.Modules.Responses.Entities.ResponseSet", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
